### ISSUE TITLE
`pod install` fails with deployment target < 13 for newest Intercom version

### ISSUE THREAD

**Issue by volesen** [cmaycumber/config-plugin-react-native-intercom#10]
Using `@intercom/intercom-react-native: "2.x"` and running a new Expo 44 SDK project from template creates the following error on the `pod install` step of `expo prebuild`:

`Specs satisfying the 'intercom-react-native (from '../node_modules/@intercom/intercom-react-native')' dependency were found, but they required a higher minimum deployment target.`

I reckon a fix is to bump the deployment target to "13" in the Podfile using a dangerous mod.

Should that be a part of the plugin?

**Comment by cmaycumber** [comment]
> I reckon a fix is to bump the deployment target to "13" in the Podfile using a dangerous mod.

I'm going to try to give this a shot today. I'm not sure how dangerous that is or if it's possible currently. I'll let you know once I give it a shot. In the meantime I'd recommend moving to `1.1.1`. If it's not building

**Comment by cmaycumber** [comment]
Try installing the latest version of the plugin `1.1.0` and using the flag `experimentalBumpMinIosPlatformVersion: true` in the config!
