### ISSUE TITLE
Could not find method implementation() for arguments [com.squareup.okhttp3:okhttp-urlconnection:4.9.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### ISSUE THREAD

**Issue by m1st1ck** [cmaycumber/config-plugin-react-native-intercom#14]
I upgraded from version 1.1.0 to 1.1.2 and my android eas build started failing.

Could not find method implementation() for arguments [com.squareup.okhttp3:okhttp-urlconnection:4.9.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by cmaycumber** [comment]
Thanks for pointing this out. I'll take a look at this today.

**Comment by cmaycumber** [comment]
@m1st1ck Can you try the latest version of the plugin?

**Comment by m1st1ck** [comment]
@cmaycumber I've updated to 1.2.0 and I still get the error
```
[stderr] A problem occurred evaluating project ':app'.
[stderr] > Could not find method implementation() for arguments [com.squareup.okhttp3:okhttp-urlconnection:4.9.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

Not sure if it is relevant but I am using

"expo": "^43.0.0",
"@intercom/intercom-react-native": "^1.1.1",
"config-plugin-react-native-intercom": "^1.2.0",

**Comment by cmaycumber** [comment]
Got it. Can you try running `expo prebuild --clean`? 

I think it could also be that's it's not backward compatible with v1.1.1 of the @intercom/intercom-react-native package. 

I can fix this if you don't want to upgrade.

**Comment by cmaycumber** [comment]
> so the `implementation 'com.squareup.okhttp3:okhttp-urlconnection:4.9.1'` is added there. By changing the config plugins order I was able to fix it but now I get some other error...

Do you think me checking for the existence would help you at all? Maybe I can run a check to make sure it doesn't get double imported. I just ran a fresh build of the example app and was able to get android running.

**Comment by m1st1ck** [comment]
I am not really sure what would be the best solution... Maybe somehow target the last occurrence of  "dependencies {" and inject it there. For me just changing the order of the config plugins is okay right now, since once we have RN 0.65 we won't need to add the `implementation("com.squareup.okhttp3:okhttp-urlconnection:4.9.1")`.

I create clean/blank project `expo init ...` and was able to narrow down my second issue to `expo-location`.
"@intercom/intercom-react-native": "^2.1.0",
"config-plugin-react-native-intercom": "^1.2.1",
"expo": "~44.0.0",
"expo-location": "~14.0.1"
not sure if this is issue for here or expo, since it occurs when I have both(might be just intercom itself and not the plugin) and I could not really figure out what is that error.

**Comment by cmaycumber** [comment]
@m1st1ck Are you still having this issue by any chance?

**Comment by cmaycumber** [comment]
Gonna close this feel free to comment so I can reopen if I can help!

**Comment by giaset** [comment]
My EAS build just started failing with the exact same error:

```
[stderr] FAILURE: Build failed with an exception.
[stderr] * Where:
[stderr] Build file '/home/expo/workingdir/build/android/app/build.gradle' line: 7
[stderr] * What went wrong:
[stderr] A problem occurred evaluating project ':app'.
[stderr] > Could not find method implementation() for arguments [com.squareup.okhttp3:okhttp-urlconnection:4.9.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

For reference, I'm on:

"expo": "^47.0.11",
"@intercom/intercom-react-native": "^4.0.1",
"config-plugin-react-native-intercom": "^1.7.0"

**Comment by giaset** [comment]
Changing the order of my plugins in app.json fixed it. In my case, `@bugsnag/plugin-expo-eas-sourcemaps` had to come before `config-plugin-react-native-intercom`
