### ISSUE TITLE
Expo SDK 44 eas build for Android fails at prebuild: config_plugins_1.AndroidConfig.Version.setMinBuildScriptExtVersion is not a function

### ISSUE THREAD

**Issue by koukoujohn** [cmaycumber/config-plugin-react-native-intercom#16]
"expo": "^44.0.6",
Expo managed: yes
expo cli version: 5.3.0
eas cli version: eas-cli/0.48.0 win32-x64 node-v14.17.6
"@intercom/intercom-react-native": "^2.1.0"
"config-plugin-react-native-intercom": "^1.2.0"

First of all thenk you for the config plugin it's invaluable in my case. I will try in the future to learn how config plugins work so that I can contribute to your project too.

I followed the instructions on your Readme, installed latest intercom through npm and your latest config plugin through expo install.

I put this in my plugins in app.json as instructed:

      [
        "config-plugin-react-native-intercom",
        {
          "iosApiKey": "private",
          "androidApiKey": "private",
          "appId": "private",
          "experimentalBumpMinIosPlatformVersion": true,
          "iosPhotoUsageDescription": "Upload images to support center"
        }
      ]

When I run eas build --platform android the build fails in the prebuild phase(on eas servers). 
With iOS I dont have any issues with building the app, it completes succesfully.

Below I will paste the Prebuild stage logs that seem to be the fail error:

- Config syncing
✖ Config sync failed

[stderr] [14:30:47] [android.projectBuildGradle]: withAndroidProjectBuildGradleBaseMod: config_plugins_1.AndroidConfig.Version.setMinBuildScriptExtVersion is not a function

[stderr] [14:30:47] TypeError: [android.projectBuildGradle]: withAndroidProjectBuildGradleBaseMod: config_plugins_1.AndroidConfig.Version.setMinBuildScriptExtVersion is not a function

I hope this is enough information to help you.

**Comment by koukoujohn** [comment]
Could this have something to do with the fact that expo SDK 44 is targeting Android SDK 30?
And in order to use intercom 2.1.0 you have to target SDK 31.

source https://github.com/intercom/intercom-react-native/releases : 
---------

Features:
We’ve added Suggested Articles to your Homescreen! Provide a better self-serve experience to your users by enabling them to answer their question before they reach out to a teammate.

Code Updates:
You Android app must target at least API level 31 to use Intercom react native SDK v2.1.0 and above.

I will try to build with previous version of @intercom/intercom-react-native 2.0.4 and let you know if this is the solution

**Comment by Snothy** [comment]
My solution was to just install config-plugin-react-native-intercom@1.1.2. The function isn't executed in that version. I guess it doesn't exist in the version of expo we're using.

**Comment by cmaycumber** [comment]
I think you're right here. I'm curious if downloading the latest version of the `@expo/config-plugins` library would fix this for you. 

I might also be able to check for the version of the plugin to prevent this.

**Comment by cmaycumber** [comment]
@koukoujohn Can you check the version of `@expo/config-plugins` installed on your repo? I just pushed an update that forces the latest version as a dev dependency.

**Comment by koukoujohn** [comment]
I can confirm that version 1.2.1 with the latest changes passed the prebuild stage and completed the build succesfully for Android EAS (managed) 😄 .

I used "@intercom/intercom-react-native": "^2.0.3" as in the example app. And in my eas.json build profile i put 
"image": "latest" (I don't know if this matters but it solved some other build issues I had)

Also the UNREAD_COUNT_CHANGE_NOTIFICATION issue didnt pop up in Android all is working as supposed

We can probably close this ticket.

Thanks @cmaycumber 😃

**Comment by ansh** [comment]
@cmaycumber So currently there is no way to use this library with jest (the package due to which this error occurs) and a version of this library that is above 1.3? Seems like a bug.
