### ISSUE TITLE
New feature: Add Data Hosting Region Configuration

### ISSUE THREAD

**Issue by koukoujohn** [cmaycumber/config-plugin-react-native-intercom#17]
For iOS, Intercom has some settings for users that want to use Data Hosting in Europe.

In iOS you can do that with changing the config plugin. Specifically for Expo users(!!) you just add this line in infoPlist in app.json:
-------
```
"infoPlist": {
  "IntercomEURegion": "true"
},
```

But for Android you need to add lines to the AndroidManifest:
-----
```
<meta-data
    android:name="io.intercom.android.sdk.use.eu.server"
    android:value="true" />
```

Would it be possible to add it (as an option) in the next version?
Here is the source: https://developers.intercom.com/installing-intercom/docs/react-native-data-hosting-region-configuration

Thanks in advance :)

**Comment by cmaycumber** [comment]
@koukoujohn Sorry this has taken so long to get it. I'm going to try to get something up tonight

**Comment by cmaycumber** [comment]
@koukoujohn This should be added in the latest version! Just use `intercomEURegion: true` in the config settings

**Comment by koukoujohn** [comment]
@cmaycumber you are awesome!!

Quick fix in the README it says "intercomEURegion": "Upload to support center"     instead of true 😅

**Comment by cmaycumber** [comment]
> @cmaycumber you are awesome!!
> 
> Quick fix in the README it says "intercomEURegion": "Upload to support center" instead of true 😅

Good spot thanks! I'll get this tweaked. I'm glad you figured out it was supposed to be true haha
