### ISSUE TITLE
EAS build (managed) fails at pre-build stage android + ios

### ISSUE THREAD

**Issue by koukoujohn** [cmaycumber/config-plugin-react-native-intercom#18]
It seems that some change from the expo side (maybe filesystem) makes the plugin fail at prebuild.

What I get from android prebuild EAS:
----

- Config syncing
✖ Config sync failed
[stderr] [23:23:15] [android.mainApplication]: withAndroidMainApplicationBaseMod: Cannot find module './Package'
[stderr] Require stack:
[stderr] - /home/expo/workingdir/build/node_modules/config-plugin-react-native-intercom/node_modules/@expo/config-plugins/build/android/index.js
[stderr] - /home/expo/workingdir/build/node_modules/config-plugin-react-native-intercom/node_modules/@expo/config-plugins/build/index.js
[stderr] - /home/expo/workingdir/build/node_modules/config-plugin-react-native-intercom/build/withIntercomReactNative.js
[stderr] - /home/expo/workingdir/build/node_modules/config-plugin-react-native-intercom/app.plugin.js
[stderr] - /home/expo/eas-build-worker/node_modules/@expo/config-plugins/build/utils/plugin-resolver.js
[stderr] - /home/expo/eas-build-worker/node_modules/@expo/config-plugins/build/plugins/withStaticPlugin.js
[stderr] - /home/expo/eas-build-worker/node_modules/@expo/config-plugins/build/plugins/withPlugins.js
[stderr] - /home/expo/eas-build-worker/node_modules/@expo/config-plugins/build/index.js
[stderr] - /home/expo/eas-build-worker/node_modules/@expo/config/build/plugins/withConfigPlugins.js
[stderr] - /home/expo/eas-build-worker/node_modules/@expo/config/build/Config.js
[stderr] - /home/expo/eas-build-worker/node_modules/@expo/config/build/index.js
[stderr] - /home/expo/eas-build-worker/node_modules/@expo/metro-config/build/ExpoMetroConfig.js
[stderr] - /home/expo/eas-build-worker/node_modules/expo-cli/build/exp.js
[stderr] - /home/expo/eas-build-worker/node_modules/expo-cli/bin/expo.js

What I get from iOS prebuild EAS:
---

- Config syncing
✖ Config sync failed
[stderr] [16:35:53] [ios.dangerous]: withIosDangerousBaseMod: Cannot find module './ios'
[stderr] Require stack:
[stderr] - /Users/expo/workingdir/build/node_modules/config-plugin-react-native-intercom/node_modules/@expo/config-plugins/build/index.js
[stderr] - /Users/expo/workingdir/build/node_modules/config-plugin-react-native-intercom/build/withIntercomReactNative.js
[stderr] - /Users/expo/workingdir/build/node_modules/config-plugin-react-native-intercom/app.plugin.js
[stderr] - /usr/local/eas-build-worker/node_modules/@expo/config-plugins/build/utils/plugin-resolver.js
[stderr] - /usr/local/eas-build-worker/node_modules/@expo/config-plugins/build/plugins/withStaticPlugin.js
[stderr] - /usr/local/eas-build-worker/node_modules/@expo/config-plugins/build/plugins/withPlugins.js
[stderr] - /usr/local/eas-build-worker/node_modules/@expo/config-plugins/build/index.js
[stderr] - /usr/local/eas-build-worker/node_modules/@expo/config/build/plugins/withConfigPlugins.js
[stderr] - /usr/local/eas-build-worker/node_modules/@expo/config/build/Config.js
[stderr] - /usr/local/eas-build-worker/node_modules/@expo/config/build/index.js
[stderr] - /usr/local/eas-build-worker/node_modules/@expo/metro-config/build/ExpoMetroConfig.js
[stderr] - /usr/local/eas-build-worker/node_modules/expo-cli/build/exp.js
[stderr] - /usr/local/eas-build-worker/node_modules/expo-cli/bin/expo.js

my dependencies and EAS diagnostics:
---

EAS CLI 0.48.2 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD  
    Utilities:
      Git: 2.33.0. - /mingw64/bin/git
    npmPackages:
      expo: ^44.0.6 => 44.0.6 
      expo-dev-client: ~0.8.4 => 0.8.4 
      expo-updates: ~0.11.6 => 0.11.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
      react-navigation: ^4.4.4 => 4.4.4
    Project workflow: managed

"@intercom/intercom-react-native": "^2.0.4",
"config-plugin-react-native-intercom": "^1.2.1",

Everything was working a few days ago, I could build just fine with the same dependencies. Now it fails everytime

**Comment by cmaycumber** [comment]
Thanks, let me take a look at this.

**Comment by koukoujohn** [comment]
@cmaycumber It seems it resolved by itself and today it's building normally.

Do you have any idea what could have caused the above errors during prebuild? Something with the dependencies the plugin uses?

I'm closing this ticket.

**Comment by cmaycumber** [comment]
> Do you have any idea what could have caused the above errors during prebuild? Something with the dependencies the plugin uses?

I'm thinking maybe it was a conflicting package? Or maybe the intercom package got a new version.

Let me know if you find anything out!
