### ISSUE TITLE
Support for managed workflow

### ISSUE THREAD

**Issue by daytonellwanger** [cmaycumber/config-plugin-react-native-intercom#19]
Are there any plans to support the Expo managed workflow?

**Comment by cmaycumber** [comment]
By managed workflow do you mean without using the dev client?

Currently, expo config plugins only work with apps using dev client so that you can add custom native code.

**Comment by daytonellwanger** [comment]
Expo docs [here](https://docs.expo.dev/introduction/managed-vs-bare/). 

Actually revisiting the differences on the latest version of Expo, there don't seem to be very many serious ones. I was worried that I wouldn't be able to use the Expo client to test my app via `expo start`, or that OTA updates wouldn't be supported once "ejecting". But it looks like maybe the only thing the managed workflow really supplies is configuration via `app.json` for things like the app icon and splash screen.
