### ISSUE TITLE
Call any intercom JS Api show "Something went wrong" on Intercom's window

### ISSUE THREAD

**Issue by TrustyTechSG** [cmaycumber/config-plugin-react-native-intercom#2]
Hi there, I have added this config plugin include intercom apiKey and appId and built with expo eas build, everything fine with the building process and import of @intercom/intercom-react-native in JS, but when call any of intercom's API, like Intercom.displayMessenger(), shows "Something went wrong", am I miss anything? Great thanks~

![WechatIMG21](https://user-images.githubusercontent.com/36871034/145951445-53b4f0f9-5045-43b7-aff0-b0bafd802928.jpeg)

**Comment by TrustyTechSG** [comment]
My fault, looks like its simply just need to call register user API like registerUnidentifiedUser before other API call. Closing this.

**Comment by dmdmd** [comment]
@TrustyTechSG would you mind showing how you solved your issue? I still get the same error when doing this:
```
	useEffect(() => {
		Intercom.registerUnidentifiedUser().then(() => Intercom.displayMessenger())
	}, [])
```
