### ISSUE TITLE
Plugin not connecting to intercom

### ISSUE THREAD

**Issue by lindanip** [cmaycumber/config-plugin-react-native-intercom#20]
Hey, I unable to set this plugin on my expo project following the README instruction. I get this message from intercom
"Intercom isn’t installed for your Android app yet".

**Comment by lindanip** [comment]
Im am using expo managed workflow. Is it possible work with this package on the managed workflow?

**Comment by cmaycumber** [comment]
> Im am using expo managed workflow. Is it possible work with this package on the managed workflow?
> 
> 

Are you using the dev-client by any chance? This plugin should only be used with the dev client which requires you running expo run:ios.

**Comment by lindanip** [comment]
No I wasn't using it, I'll install it and try again

**Comment by cmaycumber** [comment]
@lindanip Were you able to figure it out?

**Comment by cmaycumber** [comment]
Gonna close this for now. Let me know if you still have trouble setting it up I may be able to help!
