### ISSUE TITLE
EAS build failing for iOS

### ISSUE THREAD

**Issue by GabrielDierks** [cmaycumber/config-plugin-react-native-intercom#21]
I installed the `@intercom/intercom-react-native`package and config plugin with the setup in the` app.json`. Running it locally with expo prebuild works perfectly fine on android and iOS.

But once I build the app using eas build for iOS the Fastlane pipeline keeps crashing, right after finishing the Archive. The exception is:

`Uncaught Exception: -[NSNull path]: unrecognized selector sent to instance 0x7fff808aceb0
Stack:
  0   __exceptionPreprocess (in CoreFoundation)
  1   objc_exception_throw (in libobjc.A.dylib)
  2   -[NSObject(NSObject) __retain_OA] (in CoreFoundation)
  3   ___forwarding___ (in CoreFoundation)
  4   _CF_forwarding_prep_0 (in CoreFoundation)
  5   -[IDEDistributionProcessingPipeline process:] (in IDEFoundation)
  6   -[IDEDistributionPackagingStep loadFromExportOptions:error:] (in IDEFoundation)
  7   -[IDEDistributionDriver runWithDestinationPath:error:] (in IDEFoundation)
  8   -[Xcode3CommandLineBuildTool _distributeArchiveAndExit] (in Xcode3Core)
  9   -[Xcode3CommandLineBuildTool run] (in Xcode3Core)
 10   main (in xcodebuild)
 11   start (in libdyld.dylib)
`
When I archive the app with XCode it works with no problem which makes me think everything is setup correctly.

**Comment by GabrielDierks** [comment]
Hey, thanks for the quick response!

Running on expo@44.0.6
`eas-cli/0.49.0 darwin-arm64 node-v16.14.2`
`@intercom/intercom-react-native@3.0.3`
`config-plugin-react-native-intercom@1.2.1`

eas build config:

`		"preview": {
			"distribution": "internal",
			"ios": {
				"enterpriseProvisioning": "adhoc",
				"cocoapods": "1.11.2" // needed for 
			}
		},`

**Comment by GabrielDierks** [comment]
Amazing!! It worked with `@intercom/intercom-react-native 2.0.3`! Thanks for that quick heads up and you looking into it! Made my Friday!! 😎

**Comment by cmaycumber** [comment]
@GabrielDierks If you'd like to use expo 45 and the newest version of Intercom you can install the newest version!
