### ISSUE TITLE
iOS Prebuild failed on Expo 45 [Cannot add Intercom code to AppDelegate of language "objcpp"]

### ISSUE THREAD

**Issue by TrustyTechSG** [cmaycumber/config-plugin-react-native-intercom#22]
Hi, Im facing this error with EAS build after upgraded the below 3 packages, anyone know where goes wrong? thank you~

"@intercom/intercom-react-native": "^3.0.3",
"config-plugin-react-native-intercom": "^1.2.1",
"expo": "^45.0.0",

[stderr] [16:53:05] [ios.dangerous]: withIosDangerousBaseMod: Cannot add Intercom code to AppDelegate of language "objcpp"
[stderr] [16:53:05] Error: [ios.dangerous]: withIosDangerousBaseMod: Cannot add Intercom code to AppDelegate of language "objcpp"
[stderr]     at /Users/expo/workingdir/build/node_modules/config-plugin-react-native-intercom/build/withIntercomAppDelegate.js:16:23
[stderr]     at action (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/src/plugins/withMod.ts:227:23)
[stderr]     at interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
[stderr]     at interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
[stderr]     at interceptingMod (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
[stderr]     at interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
[stderr]     at interceptingMod (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
[stderr]     at interceptingMod (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
[stderr]     at action (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/plugins/createBaseMod.ts:82:21)
[stderr]     at interceptingMod (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
[stderr]     at evalModsAsync (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:172:25)
[stderr]     at compileModsAsync (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:82:10)
[stderr]     at configureManagedProjectAsync (/usr/local/eas-build-worker/node_modules/expo-cli/src/commands/eject/configureProjectAsync.ts:58:12)
[stderr]     at prebuildAsync (/usr/local/eas-build-worker/node_modules/expo-cli/src/commands/eject/prebuildAppAsync.ts:88:21)
[stderr]     at actionAsync (/usr/local/eas-build-worker/node_modules/expo-cli/src/commands/eject/prebuildAsync.ts:34:3)
bash exited with non-zero code: 1

**Comment by cmaycumber** [comment]
I think this could be related to this issue: #21 

I should be able to debug it this weekend but a possible fix might be downgrading to react-native-intercom v2 if you don't need the survey feature

**Comment by TrustyTechSG** [comment]
> I think this could be related to this issue: #21
> 
> I should be able to debug it this weekend but a possible fix might be downgrading to react-native-intercom v2 if you don't need the survey feature

Hi there, thank you for the reply, I tried downgrade @intercom/intercom-react-native to 2.0.3, but still facing the exact same error as above with EAS build. 😭

**Comment by cmaycumber** [comment]
> > I think this could be related to this issue: #21
> > I should be able to debug it this weekend but a possible fix might be downgrading to react-native-intercom v2 if you don't need the survey feature
> 
> Hi there, thank you for the reply, I tried downgrade @intercom/intercom-react-native to 2.0.3, but still facing the exact same error as above with EAS build. 😭

Going to take a look at this today! Any chance you can test it with the expo 44 SDK to see if that's the issue?

**Comment by GabrielDierks** [comment]
Can confirm that it worked for me with SDK 44 and `@intercom/intercom-react-native to 2.0.3`!

**Comment by TrustyTechSG** [comment]
> > > I think this could be related to this issue: #21
> > > I should be able to debug it this weekend but a possible fix might be downgrading to react-native-intercom v2 if you don't need the survey feature
> > 
> > 
> > Hi there, thank you for the reply, I tried downgrade @intercom/intercom-react-native to 2.0.3, but still facing the exact same error as above with EAS build. 😭
> 
> Going to take a look at this today! Any chance you can test it with the expo 44 SDK to see if that's the issue?

Hi @cmaycumber, just tried simply change expo SDK from 45.0.2 to 44.0.0, then the build at least passed the EAS pre-build stage. (SDK 45 failed during EAS pre-build every time)

**Comment by cmaycumber** [comment]
The newest version here: `"config-plugin-react-native-intercom": "1.3.0"` should fix the issues!

**Comment by TrustyTechSG** [comment]
> The newest version here: `"config-plugin-react-native-intercom": "1.3.0"` should fix the issues!

Yes, build passed with 1.3.0, big thanks~~ you make my day : )
