### ISSUE TITLE
Expo prebuild command fails

### ISSUE THREAD

**Issue by maxenceg** [cmaycumber/config-plugin-react-native-intercom#24]
Hi!

I have an error whenever I run `expo prebuild`
I'm in a managed workflow of an expo project, and when I run the command `expo prebuild`, I get the following error:
"[ios.dangerous]: withIosDangerousBaseMod: Cannot add Intercom code to AppDelegate of language "objc""

![image](https://user-images.githubusercontent.com/38657323/167858705-54377f68-f4f9-47e7-94c7-ed6f9face846.png)

Is there something I didn't do correctly?

**Comment by cmaycumber** [comment]
@maxenceg What version of Expo are you using? I'm thinking the error is due to using version 44 w/ version 1.3.0 of the plugin

**Comment by cmaycumber** [comment]
If you'd like to use version 44 of Expo, downgrading the plugin to version 1.2.3 might fix the issue

**Comment by maxenceg** [comment]
@cmaycumber Thanks for the fast answer!!

I'm using version 1.3.0 indeed
However, I can't install version 1.2.3 as there's no match found

I'll try 1.2.1

**Comment by maxenceg** [comment]
Alright, thanks for your help 😊
