### ISSUE TITLE
Add Support for Intercom Push Notifications

### ISSUE THREAD

**Issue by SergeWilfried** [cmaycumber/config-plugin-react-native-intercom#3]
Thanks for this package. I was wondering if you had plan to add Push Notifications to it ?

**Comment by cmaycumber** [comment]
Yeah it should be simple! I'll try to add those in tonight!

**Comment by SergeWilfried** [comment]
Awesome thanks !

**Comment by cmaycumber** [comment]
In the meantime if you want to add this in now you can do something like this: 

```js
import Intercom from '@intercom/intercom-react-native';
...
Intercom.sendTokenToIntercom(deviceToken?.data);
```

**Comment by SergeWilfried** [comment]
Looks great ! But I am wondering if the firebase messaging config will work with the current setup.

**Comment by GautierT** [comment]
> In the meantime if you want to add this in now you can do something like this:
> 
> ```js
> import Intercom from '@intercom/intercom-react-native';
> ...
> Intercom.sendTokenToIntercom(deviceToken?.data);
> ```

Hi @cmaycumber 
What is the `deviceToken` that you talk about ?

Thanks a lot.

**Comment by GautierT** [comment]
For expo I get it like that ?
https://docs.expo.dev/push-notifications/push-notifications-setup/

```
import * as Notifications from 'expo-notifications';

const token = (await Notifications.getExpoPushTokenAsync()).data;
```

**Comment by GautierT** [comment]
And an other question : 
What should I enter here on Intercom settings ?
![image](https://user-images.githubusercontent.com/6089653/146755352-081a794d-6b6e-4ed1-949a-f3d7a1f86c12.png)

**Comment by GautierT** [comment]
The devicePushToken is from `await Notifications.getDevicePushTokenAsync()`

```
import Intercom from '@intercom/intercom-react-native';
import * as Notifications from 'expo-notifications';

...
const devicePushToken = (await Notifications.getDevicePushTokenAsync()).data;
Intercom.sendTokenToIntercom(devicePushToken);
```

**Comment by cmaycumber** [comment]
> The devicePushToken is from `await Notifications.getDevicePushTokenAsync()`

This is correct. I can send more of my implementation if need be; this shouldn't be an issue once it get's added to the normal setup.

**Comment by PiotrSzlagura** [comment]
@cmaycumber Hi, do I understand correctly that while using this package, the only thing to do is `Intercom.sendTokenToIntercom(devicePushToken);` and Intercom push notifications should work, both on Android and iOS?

**Comment by cmaycumber** [comment]
> @cmaycumber Hi, do I understand correctly that while using this package, the only thing to do is `Intercom.sendTokenToIntercom(devicePushToken);` and Intercom push notifications should work, both on Android and iOS?

@PiotrSzlagura Yes, that's correct

**Comment by cmaycumber** [comment]
Going to start tracking this here #11
