### ISSUE TITLE
EU region support not working

### ISSUE THREAD

**Issue by GabrielDierks** [cmaycumber/config-plugin-react-native-intercom#34]
Hey! This is not your fault. I was talking to Intercom support today and it seems like the docs for React Native are outdated.

**So in order for iOS to work you need to add:**

```
"infoPlist": {
  "IntercomRegion": "EU"
},

```
instead of:

```
"infoPlist": {
  "IntercomEURegion": "true"
},
```

its updated in the [docs for native iOS](https://developers.intercom.com/installing-intercom/docs/ios-data-hosting-region-configuration)

Maybe you can also add this to your Readme since its still wrong in the intercom docs :).

**For Android its:**

```
<meta-data
        android:name="io.intercom.android.sdk.server.region"
        android:value="@integer/intercom_server_region_eu" />
```

instead of:

```
<meta-data
    android:name="io.intercom.android.sdk.use.eu.server"
    android:value="true" />
```
    
Also this is only mentioned in the [docs for the native Android implementation](https://developers.intercom.com/installing-intercom/docs/android-data-hosting-region-configuration)

**Comment by GabrielDierks** [comment]
I made a [PR](https://github.com/cmaycumber/config-plugin-react-native-intercom/pull/35)

Would be nice if you can merge this and release it soon because we need this in our implementation :)

**Comment by cmaycumber** [comment]
#35
