### ISSUE TITLE
iOS build failing - RCTEventEmitter errors 

### ISSUE THREAD

**Issue by jseitel** [cmaycumber/config-plugin-react-native-intercom#4]
Hi there, was hoping to integrate intercom into my Expo app but ran into an issue creating a development build on Expo EAS.  Seems as if there's a dependency missing in the iOS project. Here's the output from the Fastlane logs:

```
› Compiling @intercom/intercom-react-native Pods/intercom-react-native » IntercomHelpCenterHelpers.m

❌  (../../../../Public/React-Core/React/RCTEventEmitter.h:15:1)

@interface RCTEventEmitter : NSObject <RCTBridgeModule, RCTJSInvokerModule, RCTInvalidating>
^ duplicate interface definition for class 'RCTEventEmitter'

❌  (ios/Pods/Headers/Public/React-Core/React/RCTEventEmitter.h:17:40)

  15 | @interface RCTEventEmitter : NSObject <RCTBridgeModule, RCTJSInvokerModule, RCTInvalidating>
  16 | 
> 17 | @property (nonatomic, weak) RCTBridge *bridge;
     |                                        ^ property has a previous declaration
  18 | 
  19 | - (instancetype)initWithDisabledObservation;
  20 | 

❌  (node_modules/@intercom/intercom-react-native/ios/IntercomEventEmitter.h:9:35)

   7 | #endif
   8 | 
>  9 | @interface IntercomEventEmitter : RCTEventEmitter
     |                                   ^ definition of 'RCTEventEmitter' must be imported from module 'React.RCTEventEmitter' before it is required
  10 | @end
  11 | 
```

Unfortunately I'm very new both to RN and Expo, so I'm probably of limited use figuring out what's going on, but please let me know if I can do anything to help.

**Comment by cmaycumber** [comment]
> Hi there, was hoping to integrate intercom into my Expo app but ran into an issue creating a development build on Expo EAS. Seems as if there's a dependency missing in the iOS project. Here's the output from the Fastlane logs:
> 
> ```
> › Compiling @intercom/intercom-react-native Pods/intercom-react-native » IntercomHelpCenterHelpers.m
> 
> ❌  (../../../../Public/React-Core/React/RCTEventEmitter.h:15:1)
> 
> @interface RCTEventEmitter : NSObject <RCTBridgeModule, RCTJSInvokerModule, RCTInvalidating>
> ^ duplicate interface definition for class 'RCTEventEmitter'
> 
> ❌  (ios/Pods/Headers/Public/React-Core/React/RCTEventEmitter.h:17:40)
> 
>   15 | @interface RCTEventEmitter : NSObject <RCTBridgeModule, RCTJSInvokerModule, RCTInvalidating>
>   16 | 
> > 17 | @property (nonatomic, weak) RCTBridge *bridge;
>      |                                        ^ property has a previous declaration
>   18 | 
>   19 | - (instancetype)initWithDisabledObservation;
>   20 | 
> 
> ❌  (node_modules/@intercom/intercom-react-native/ios/IntercomEventEmitter.h:9:35)
> 
>    7 | #endif
>    8 | 
> >  9 | @interface IntercomEventEmitter : RCTEventEmitter
>      |                                   ^ definition of 'RCTEventEmitter' must be imported from module 'React.RCTEventEmitter' before it is required
>   10 | @end
>   11 | 
> ```
> 
> Unfortunately I'm very new both to RN and Expo, so I'm probably of limited use figuring out what's going on, but please let me know if I can do anything to help.

Thanks for pointing this out. I'll try to look into this. What version of `expo` and `@intercom/react-native-intercom` are you currently on?

**Comment by jseitel** [comment]
I'm on expo 44.0 and @intercom/react-native-intercom 1.1.1.  I dug in a little bit, here's what I found:

* Step one, I removed all intercom stuff, did an `expo prebuild` and tried build in Expo. Everything worked!
* Step two, added back the intercom code (with the config plugin), ran `expo prebuild` again -> failed with same errors as above
* Step three, tried downgrading the versions of @intercom/react-native-intercom from 1.1.1 through every release all the way down to 1.0 (running prebuild each time).  Same failures.

I think the one thing we can glean from that is that it's not specific to EAS builds, and doesn't seem to be a recent regression in the intercom package.

Btw, I forgot to mention, but the android build is working fine.

**Comment by jseitel** [comment]
I'll also mention, I then tried editing some of the native files directly to see if I could coerce intercom into working, but every time I solved one missing dependency it would choke on another further down the tree. Unfortunately I don't know enough about the underlying packages to poke much deeper than that.

**Comment by cmaycumber** [comment]
Are you using yarn v2 by any chance? The newer versions of expo-module-linker might have an issue with auto-linking modules with yarn v2.

This might not be the issue, but I do know that expo v44 requires a newer version that was causing our project to fail.

**Comment by jseitel** [comment]
Nope, I'm on yarn 1.22.10.  Would recommend trying expo 43 to see if it resolves the issue?

**Comment by jseitel** [comment]
Just tried with expo 43, no issues.  Thanks for your help man.  Would you prefer I keep this issue open for tracking or close it?

**Comment by cmaycumber** [comment]
Yeah let's keep it open. I'm going to be keeping an eye out for a fix, hopefully the issue resolves itself soon

**Comment by AndrewIngram** [comment]
This issue popped up as soon as I tried upgrading to Expo 44, it was working perfectly in 43.

**Comment by cmaycumber** [comment]
I recently upgraded to expo 44. I think it required me updating the @intercom/react-native-intercom package as well.

Let me know if that solves it.

**Comment by AndrewIngram** [comment]
Do you know what version of that package you have? I tried upgrading to the lasted, but that's a major version (1->2) change and it seemed to break even more.

**Comment by cmaycumber** [comment]
I'll shoot over my package.json. Also make sure you're running pre-build beforehand, there's been some weird scenarios where I need to delete the iOS/Android folders because of caching as well.

**Comment by AndrewIngram** [comment]
I think I managed to get it to build with 1.1.1. Looks like 2.x isn't possible without increasing the min iOS version, is that even possible with expo?

**Comment by cmaycumber** [comment]
Hey sorry, you're right I'm pinned at `"@intercom/intercom-react-native": "1.1.1",`

**Comment by cmaycumber** [comment]
Going to close this for now and track the issue of bumping the min iOS version in #10
