### ISSUE TITLE
upgrade to @expo/config-plugins@5.0.0

### ISSUE THREAD

**Issue by Norfeldt** [cmaycumber/config-plugin-react-native-intercom#41]
Is there any chance of upgrading to the latest `@expo/config-plugins`? 🙂

**Comment by SimenB** [comment]
relevant discussion: https://github.com/jakobo/expo-community-flipper/issues/16#issuecomment-1220254201

**Comment by cmaycumber** [comment]
Yeah I can do this it shouldn't be too bad!

**Comment by cmaycumber** [comment]
This should be in the latest version here: https://www.npmjs.com/package/config-plugin-react-native-intercom/v/1.6.10
