### ISSUE TITLE
`@intercom/react-native` version 4

### ISSUE THREAD

**Issue by ckrodrigues** [cmaycumber/config-plugin-react-native-intercom#45]
First of all I'd like to thank you for developing this plugin.
I'm trying to make Intercom to work with our app and I installed `@intercom/react-native` v4.0.1 but I'm having multiple issues using it. First issue is that the iOS app crashes once I call `loginUnidentifiedUser` or `loginUserWithUserAttributes`. I also see `Something's gone wrong` when I call `Intercom.presentSpace(Space.helpCenter)` and `Intercom.displayMessenger` (which is deprecated by the way). I assume this plugin is not compatible with the new version of Intercom. I'll do some tests with version 3 to see if it works to make sure the issue is not something on my end, but I'd like to ask if there's any plan on supporting version 4 and if you're interested in accepting collaborators to build that.

**Comment by enagorny** [comment]
I've just faced this issue as well. I'm new to intercom and just starting to use it. For now I've decided to use v3.0.5. But it will be great if this config plugin will work with v4 as it has a new features.
I'm glad to help you to adopt this to v4 but I don't know where to start.

**Comment by cmaycumber** [comment]
This was just published! Thanks a ton @enagorny

**Comment by ansh** [comment]
Thank you for your hard work @enagorny and @cmaycumber 

I appreciate you keeping the package up-to-date and merging PRs promptly
