### ISSUE TITLE
IOS build fails

### ISSUE THREAD

**Issue by BasilJohn** [cmaycumber/config-plugin-react-native-intercom#53]
"@intercom/intercom-react-native": "^4.0.1",
    "config-plugin-react-native-intercom": "^1.8.0",
    "expo": "^46.0.0",

App.json

 "plugins": [
      "@react-native-firebase/app",
      [
        "expo-build-properties",
        { "android": { "compileSdkVersion": 33, "targetSdkVersion": 33 }}
      ],
      [
        "config-plugin-react-native-intercom",
        {
         "iosApiKey": "private",
         "androidApiKey": "private",
         "appId": "private",
         "experimentalBumpMinIosPlatformVersion": true
        }
      ],
      [
        "expo-image-picker",
        {
          "photosPermission": "The app accesses your photos to let you share them with your friends."
        }
      ]
    ],

When I build app using eas build I get the below error.

<img width="920" alt="Screenshot 2023-01-24 at 10 57 08" src="https://user-images.githubusercontent.com/9947986/214274184-5bc5963a-c710-45b9-af68-bafe3f41203d.png">

Any thoughts on this please.

**Comment by enagorny** [comment]
@BasilJohn have you tried to use the `--clear-cache` as eas suggest?
```eas build --clear-cache```

**Comment by BasilJohn** [comment]
@enagorny  I tried and got the same error.

**Comment by jmorrice** [comment]
[Intercom only supports iOS 13 and above](https://stackoverflow.com/a/70789836), so you need to set:

`
ios: {
      deploymentTarget: "13.0"
},`

**Comment by BasilJohn** [comment]
> @BasilJohn does it work for you [#53 (comment)](https://github.com/cmaycumber/config-plugin-react-native-intercom/issues/53#issuecomment-1430259528) ?

Yes it does thanks
