### ISSUE TITLE
[IOS] Not working on SDK48 `loginUnidentifiedUser` crashes

### ISSUE THREAD

**Issue by wcastand** [cmaycumber/config-plugin-react-native-intercom#56]
i've upgraded to sdk 48 and intercom on IOS seems to not work as expected, nothing crashes but i get a something went wrong in the intercom window that opens. Was working fine on sdk47.

sdk48 is on hermes by default and use a new flex support so not sure if that could be the reason. Might also be an issue in the intercom dependency and have nothing to do with the config-plugin.

![Screenshot 2023-03-03 at 12 08 50](https://user-images.githubusercontent.com/2178244/222705587-8669f472-ebc8-4497-b18d-915290becd07.png)

**Comment by abponcio** [comment]
Same issue goes for me, once I try to loginidentifieduser it just crashes the app

**Comment by wcastand** [comment]
![Screenshot 2023-03-06 at 15 01 38](https://user-images.githubusercontent.com/2178244/223131505-f9706459-3908-46bc-a470-a3713c1a654d.png)

**Comment by abponcio** [comment]
I ended up downgrading to 47 for now until then ill check now and then if it gets fixed

**Comment by elmaxe** [comment]
We are experiencing the same problem after updating to SDK48.

@wcastand are you saying it works without the notifications stuff ?

**Comment by FutureFutureTo** [comment]
Yep, I've run into this as well. Unfortunately, I am not versed enough to build my own custom module...Any help here would be greatly appreciated :)

Thanks

**Comment by elmaxe** [comment]
Found this fork: https://github.com/fobos531/config-plugin-react-native-intercom/commit/ed7e28432fb359104455d3a5d46151ad55f17f4a

Anyone know if those chages fixes things?

**Comment by eexit** [comment]
Hello,

Not an expert here, but anyone tested with updated dependencies? https://github.com/cmaycumber/config-plugin-react-native-intercom/pull/55

Thanks.

**Comment by elmaxe** [comment]
> Hello,
> 
> Not an expert here, but anyone tested with updated dependencies? #55
> 
> Thanks.

Android shouldn't affect IOS. It works fine on android with expo 48

**Comment by FutureFutureTo** [comment]
> [](https://github.com/fobos531/config-plugin-react-native-intercom/commit/ed7e28432fb359104455d3a5d46151ad55f17f4a)



> Found this fork: [fobos531@ed7e284](https://github.com/fobos531/config-plugin-react-native-intercom/commit/ed7e28432fb359104455d3a5d46151ad55f17f4a)
> 
> Anyone know if those chages fixes things?

I guess I'll give this fork a shot

**Comment by giaset** [comment]
Broken for me as well... blocked from upgrading to Expo 48 for now

**Comment by giaset** [comment]
Replacing `YES` with `\[super application:application didFinishLaunchingWithOptions:launchOptions\]` in `withIntercomIOS.ts` fixes the issue, as demonstrated by this fork https://github.com/fobos531/config-plugin-react-native-intercom

@cmaycumber -- any chance we can get this fix into 1.9.0? Thanks 🙏

**Comment by giaset** [comment]
Relevant AppDelegate diff for this new version of React Native: https://react-native-community.github.io/upgrade-helper/?from=0.70.5&to=0.71.3#RnDiffApp-ios-RnDiffApp-AppDelegate.mm

**Comment by elmaxe** [comment]
Nice find @giaset

**Comment by enagorny** [comment]
until npm release is done you can install package from the github `npm install 'https://gitpkg.now.sh/cmaycumber/config-plugin-react-native-intercom/packages/intercom-react-native?main'`
