### ISSUE TITLE
Update @expo/config-plugins

### ISSUE THREAD

**Issue by dillondow24** [cmaycumber/config-plugin-react-native-intercom#62]
Build warning:

```
Expected package @expo/config-plugins@~6.0.0
Found invalid:
  @expo/config-plugins@5.0.4
```

`npm why @expo/config-plugins` output:
```
node_modules/config-plugin-react-native-intercom/node_modules/@expo/config-plugins
  @expo/config-plugins@"^5.0.4" from config-plugin-react-native-intercom@1.10.1
```

Should this dependency be updated to `@expo/config-plugins@~6.0.0` for expo 48?

**Comment by billinghamj** [comment]
Now needs to be bumped again for Expo 49 @cmaycumber

**Comment by cmaycumber** [comment]
Got it. Let me try to get something up

**Comment by LeoAnt02** [comment]
Any update on this @cmaycumber ?

**Comment by jferrettiboke** [comment]
I've created a PR to fix this on Expo SDK 49. Waiting for approval. https://github.com/cmaycumber/config-plugin-react-native-intercom/pull/69

**Comment by jferrettiboke** [comment]
For now, as a temporary solution, you can resolve the issue by setting the version in `resolutions` within your `package.json` file. After that, attempt to reinstall the dependencies using your package manager.

```json
{
  ...
  "scripts": { ... },
  "dependencies": { ... },
  "resolutions": {
    "@expo/config-plugins": "~7.2.2"
  }
}
```

The version `"@expo/config-plugins": "~7.2.2"` is the one that works with the latest Expo SDK 49 as of the time of writing. To ensure you are using the correct version, run `npx expo-doctor@latest` before modifying the `resolutions` section in your `package.json`. `expo-doctor` will identify any issues and recommend the appropriate version based on your current Expo SDK.

If you are using a monorepo, make sure to place the `resolutions` section in the root `package.json`.

I hope this helps in the meantime while waiting for my PR to be approved and merged. This solution is also useful for those of you who have not yet upgraded to Expo SDK 49. 🫶
