### ISSUE TITLE
Issue while running in EAS: Intercom/Intercom.h file not found

### ISSUE THREAD

**Issue by ovidb** [cmaycumber/config-plugin-react-native-intercom#68]
All of a sudden from today we started getting this error while building in EAS

![eas-intercom](https://github.com/cmaycumber/config-plugin-react-native-intercom/assets/1531356/9d878027-0820-4903-9289-dafd27c94a78)

No version numbers of our packages seem to have changed - and running a build that previously passed successfully also now fails

We checked both `react-native-intercom` and `config-plugin-react-native-intercom`.

**Comment by enagorny** [comment]
We had this issue today as well. And now it's gone.
Not sure what helped
1. upgraded to latest version of eas-cli
2. rm node_modules & npm install
3. or expo/intercom team fixed something

but now it works for me.

**Comment by elmaxe** [comment]
We had the same issue yesterday, haven't checked today yet

**Comment by ovidb** [comment]
The issue for us was `eas-cli` as well. We were using the latest which at the time was [`3.15.0`](https://github.com/expo/eas-cli/releases/tag/v3.15.0). 

Forcing the the app to use a previous version (3.14.0) fixed it.

We've done that in `eas.json`

```
{
  "cli": {
    "version": "= 3.14.0"
  },
  ...
}
```

**Comment by elmaxe** [comment]
It worked for us with 3.15.0
