### ISSUE TITLE
Messenger stuck in loading state on Android, possibly for EU apps only

### ISSUE THREAD

**Issue by colemerrick** [cmaycumber/config-plugin-react-native-intercom#71]
The messenger doesn't load on Android for the following versions:

"expo": "^48.0.0"
"@intercom/intercom-react-native": "^4.0.1",
"config-plugin-react-native-intercom": "^1.10.1"

It works on iOS.

Might possibly be related to https://github.com/cmaycumber/config-plugin-react-native-intercom/issues/65 - only this is actually for an EU app.  

We have `"IntercomRegion": "EU"` set in the infoPlist of app.json and `intercomEURegion: 'true'` set in the app.config.js for Android.  We have tried both the displayMessenger() function which seems to be deprecated in v4 of @intercom/intercom-react-native function, and the present() function.

**Comment by colemerrick** [comment]
Forgot to comment and close - turns out it was not an EU intercom account after all.

**Comment by Joshandrews43** [comment]
@colemerrick I also have this issue on IOS. I have no EU settings set up. How did you solve this?
