### ISSUE TITLE
Android - No virtual method toString(Z)Ljava/lang/String; in class Lokhttp3/Cookie; or its super classes (declaration of 'okhttp3.Cookie' appears in base.apk!classes5.dex)

### ISSUE THREAD

**Issue by m1st1ck** [cmaycumber/config-plugin-react-native-intercom#9]
We are getting a lot of error - `No virtual method toString(Z)Ljava/lang/String; in class Lokhttp3/Cookie; or its super classes (declaration of 'okhttp3.Cookie' appears in base.apk!classes5.dex)`. I could not really reproduce it on my of the Android devices I have access to.

The solution is on intercom installing guide, however I am not sure how to add it with config plugin.
https://developers.intercom.com/installing-intercom/docs/react-native-installation
![image](https://user-images.githubusercontent.com/6284259/154055916-922b1163-b272-45e3-8e19-dc8172362c8e.png)

I guess it will also resolve at some point when Expo upgrades to React Native  >= 0.65, but would be great if it can be handled before that

**Comment by cmaycumber** [comment]
Thanks for pointing this out. I think it should be an easy fix.

**Comment by cmaycumber** [comment]
Should be solved in the latest version `1.0.3`
